const nationality = [
  { value: "AFG", option: "AFGHANISTAN" },
  { value: "ALB", option: "ALBANIA" },
  { value: "DZA", option: "ALGERIA" },
  { value: "ASM", option: "AMERICAN SAMOA" },
  { value: "AND", option: "ANDORRA" },
  { value: "AGO", option: "ANGOLA" },
  { value: "AIA", option: "ANGUILLA" },
  { value: "ATA", option: "ANTARCTICA" },
  { value: "ATG", option: "ANTIGUA AND BARBUDA" },
  { value: "ARG", option: "ARGENTINA" },
  { value: "ARM", option: "ARMENIA" },
  { value: "ABW", option: "ARUBA" },
  { value: "AUS", option: "AUSTRALIA" },
  { value: "AUT", option: "AUSTRIA" },
  { value: "AZE", option: "AZERBAIJAN" },
  { value: "BHS", option: "BAHAMAS" },
  { value: "BHR", option: "BAHRAIN" },
  { value: "BGD", option: "BANGLADESH" },
  { value: "BRB", option: "BARBADOS" },
  { value: "BLR", option: "BELARUS" },
  { value: "BEL", option: "BELGIUM" },
  { value: "BLZ", option: "BELIZE" },
  { value: "BEN", option: "BENIN" },
  { value: "BMU", option: "BERMUDA" },
  { value: "BTN", option: "BHUTAN" },
  { value: "BOL", option: "BOLIVIA" },
  { value: "BIH", option: "BOSNIA AND HERZEGOVINA" },
  { value: "BWA", option: "BOTSWANA" },
  { value: "BVT", option: "BOUVET ISLAND" },
  { value: "BRA", option: "BRAZIL" },
  { value: "IOT", option: "BRITISH INDIAN OCEAN TERRITORY" },
  { value: "GBN", option: "BRITISH NATIONAL OVERSEAS" },
  { value: "GBO", option: "BRITISH OVERSEAS CITIZENS" },
  { value: "GBP", option: "BRITISH PROTECTED PERSON" },
  { value: "GBS", option: "BRITISH SUBJECT" },
  { value: "BRN", option: "BRUNEI DARUSSALAM" },
  { value: "BGR", option: "BULGARIA" },
  { value: "BFA", option: "BURKINA FASO" },
  { value: "BDI", option: "BURUNDI" },
  { value: "KHM", option: "CAMBODIA" },
  { value: "CMR", option: "CAMEROON" },
  { value: "CAN", option: "CANADA" },
  { value: "CPV", option: "CAPE VERDE" },
  { value: "CYM", option: "CAYMAN ISLANDS" },
  { value: "CAF", option: "CENTRAL AFRICAN REPUBLIC" },
  { value: "TCD", option: "CHAD" },
  { value: "CHL", option: "CHILE" },
  { value: "CHN", option: "CHINA" },
  { value: "CXR", option: "CHRISTMAS ISLAND" },
  { value: "CCK", option: "COCOS ISLANDS" },
  { value: "COL", option: "COLOMBIA" },
  { value: "COM", option: "COMOROS" },
  { value: "COG", option: "CONGO" },
  { value: "COK", option: "COOK ISLANDS" },
  { value: "CRI", option: "COSTA RICA" },
  { value: "CIV", option: "COTE D'IVOIRE" },
  { value: "HRV", option: "CROATIA" },
  { value: "CUB", option: "CUBA" },
  { value: "CYP", option: "CYPRUS" },
  { value: "CZE", option: "CZECH REPUBLIC" },
  { value: "PRK", option: "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA" },
  { value: "DPR", option: "DEMOCRATIC PEOPLES REPUBLIC OF KOREA" },
  { value: "COD", option: "DEMOCRATIC REPUBLIC OF THE CONGO" },
  { value: "DNK", option: "DENMARK" },
  { value: "DJI", option: "DJIBOUTI" },
  { value: "DMA", option: "DOMINICA" },
  { value: "DOM", option: "DOMINICAN REPUBLIC" },
  { value: "ECU", option: "ECUADOR" },
  { value: "EGY", option: "EGYPT" },
  { value: "SLV", option: "EL SALVADOR" },
  { value: "GNQ", option: "EQUATORIAL GUINEA" },
  { value: "ERI", option: "ERITREA" },
  { value: "EST", option: "ESTONIA" },
  { value: "ETH", option: "ETHIOPIA" },
  { value: "EUE", option: "EUROPEAN UNION LAISSER PASSER" },
  { value: "FLK", option: "FALKLAND ISLAND (MALVINAS)" },
  { value: "FRO", option: "FAROE ISLANDS" },
  { value: "FJI", option: "FIJI" },
  { value: "FIN", option: "FINLAND" },
  { value: "FXX", option: "FINLAND, METROPOLITAN" },
  { value: "FRA", option: "FRANCE" },
  { value: "GUF", option: "FRENCH GUIANA" },
  { value: "PYF", option: "FRENCH POLYNESIA" },
  { value: "ATF", option: "FRENCH SOUTHERN TERRITORIES" },
  { value: "GAB", option: "GABON" },
  { value: "GMB", option: "GAMBIA" },
  { value: "GEO", option: "GEORGIA" },
  { value: "DGR", option: "GERMANY" },
  { value: "DEU", option: "GERMANY" },
  { value: "GHA", option: "GHANA" },
  { value: "GIB", option: "GIBRALTAR" },
  { value: "GRC", option: "GREECE" },
  { value: "GRL", option: "GREENLAND" },
  { value: "GRD", option: "GRENADA" },
  { value: "GLP", option: "GUADELOUPE" },
  { value: "GUM", option: "GUAM" },
  { value: "GTM", option: "GUATEMALA" },
  { value: "GNB", option: "GUIENA-BISSAU" },
  { value: "GIN", option: "GUINEA" },
  { value: "GUY", option: "GUYANA" },
  { value: "HTI", option: "HAITI" },
  { value: "HMD", option: "HEARD AND MCDONALD ISLANDS" },
  { value: "VAT", option: "HOLY SEE (VATICAN CITY STATE)" },
  { value: "HND", option: "HONDURAS" },
  { value: "HKG", option: "HONG KONG" },
  { value: "HUN", option: "HUNGARY" },
  { value: "ISL", option: "ICELAND" },
  { value: "IND", option: "INDIA" },
  { value: "IDN", option: "INDONESIA" },
  { value: "IRN", option: "IRAN" },
  { value: "IRQ", option: "IRAQ" },
  { value: "IRL", option: "IRELAND" },
  { value: "ISR", option: "ISRAEL" },
  { value: "ITA", option: "ITALY" },
  { value: "JAM", option: "JAMAICA" },
  { value: "JPN", option: "JAPAN" },
  { value: "JOR", option: "JORDAN" },
  { value: "KAZ", option: "KAZAKHSTAN" },
  { value: "KEN", option: "KENYA" },
  { value: "KIR", option: "KIRIBATI" },
  { value: "KWT", option: "KUWAIT" },
  { value: "KGZ", option: "KYRGYZSTAN" },
  { value: "LAO", option: "LAO PDR" },
  { value: "LVA", option: "LATVIA" },
  { value: "LBN", option: "LEBANON" },
  { value: "LSO", option: "LESOTHO" },
  { value: "LBR", option: "LIBERIA" },
  { value: "LBY", option: "LIBYA" },
  { value: "LIE", option: "LIECHTENSTEIN" },
  { value: "LTU", option: "LITHUANIA" },
  { value: "LUX", option: "LUXEMBOURG" },
  { value: "MAC", option: "MACAU" },
  { value: "MDG", option: "MADAGASCAR" },
  { value: "MWI", option: "MALAWI" },
  { value: "MYS", option: "MALAYSIA" },
  { value: "MDV", option: "MALDIVES" },
  { value: "MLI", option: "MALI" },
  { value: "MLT", option: "MALTA" },
  { value: "MHL", option: "MARSHALL ISLANDS" },
  { value: "MTQ", option: "MARTINIQUE" },
  { value: "MRT", option: "MAURITANIA" },
  { value: "MUS", option: "MAURITIUS" },
  { value: "MYT", option: "MAYOTTE" },
  { value: "MEX", option: "MEXICO" },
  { value: "FSM", option: "MICRONESIA,FEDERATED STATES OF" },
  { value: "MCO", option: "MONACO" },
  { value: "MNG", option: "MONGOLIA" },
  { value: "MNE", option: "MONTENEGRO" },
  { value: "MSR", option: "MONTSERRAT" },
  { value: "MAR", option: "MOROCCO" },
  { value: "MOZ", option: "MOZAMBIQUE" },
  { value: "MMR", option: "MYANMAR" },
  { value: "NAM", option: "NAMIBIA" },
  { value: "NRU", option: "NAURU" },
  { value: "NNS", option: "NEGARA-NEGARA SUMBER" },
  { value: "NPL", option: "NEPAL" },
  { value: "NLD", option: "NETHERLANDS" },
  { value: "ANT", option: "NETHERLANDS ANTILLES" },
  { value: "NTZ", option: "NEUTRAL ZONE" },
  { value: "NCL", option: "NEW CELEDONIA" },
  { value: "NZL", option: "NEW ZEALAND" },
  { value: "NIC", option: "NICARAGUA" },
  { value: "NER", option: "NIGER" },
  { value: "NGA", option: "NIGERIA" },
  { value: "ZZD", option: "NIL" },
  { value: "NIU", option: "NIUE" },
  { value: "NFK", option: "NORFOLK ISLAND" },
  { value: "MNP", option: "NORTHERN MARIANA ISLANDS" },
  { value: "NOR", option: "NORWAY" },
  { value: "OMN", option: "OMAN" },
  { value: "PAK", option: "PAKISTAN" },
  { value: "PLW", option: "PALAU" },
  { value: "PAL", option: "PALESTINE" },
  { value: "PSE", option: "PALESTINE" },
  { value: "PAN", option: "PANAMA" },
  { value: "PNG", option: "PAPUA NEW GUINEA" },
  { value: "PRY", option: "PARAGUAY" },
  { value: "PER", option: "PERU" },
  { value: "PHL", option: "PHILIPPINES" },
  { value: "PCN", option: "PITCAIRN ISLAND" },
  { value: "POL", option: "POLAND" },
  { value: "PRT", option: "PORTUGAL" },
  { value: "PRI", option: "PUERTO RICO" },
  { value: "QAT", option: "QATAR" },
  { value: "XXC", option: "REFUGEE" },
  { value: "XXB", option: "REFUGEE ARTICLE 1/1951" },
  { value: "MDA", option: "REP OF MOLDOVA" },
  { value: "RKS", option: "REP. KOSOVO" },
  { value: "KOR", option: "REPUBLIC OF KOREA" },
  { value: "KOS", option: "REPUBLIC OF KOSOVO" },
  { value: "MKD", option: "REPUBLIC OF MACEDONIA" },
  { value: "ROS", option: "REPUBLIC OF SOMALILAND" },
  { value: "SSD", option: "REPUBLIC OF SOUTH SUDAN" },
  { value: "REU", option: "REUNION" },
  { value: "ROM", option: "ROMANIA" },
  { value: "ROU", option: "ROMANIA" },
  { value: "RUS", option: "RUSSIA" },
  { value: "RWA", option: "RWANDA" },
  { value: "SHN", option: "SAINT HELENA" },
  { value: "KNA", option: "SAINT KITTS AND NEVIS" },
  { value: "LCA", option: "SAINT LUCIA" },
  { value: "SPM", option: "SAINT PIERRE AND MIQUELON" },
  { value: "VCT", option: "SAINT VINCENT AND THE GRENADINES" },
  { value: "WSM", option: "SAMOA" },
  { value: "SMR", option: "SAN MARINO" },
  { value: "STP", option: "SAO TOME AND PRINCIPE" },
  { value: "SAU", option: "SAUDI ARABIA" },
  { value: "SEN", option: "SENEGAL" },
  { value: "SER", option: "SERBIA" },
  { value: "SRB", option: "SERBIA" },
  { value: "SCG", option: "SERBIA AND MONTENEGRO" },
  { value: "SYC", option: "SEYCHELLES" },
  { value: "SLE", option: "SIERRA LEONE" },
  { value: "SGP", option: "SINGAPORE" },
  { value: "SVK", option: "SLOVAKIA" },
  { value: "SVN", option: "SLOVENIA" },
  { value: "SLB", option: "SOLOMON ISLANDS" },
  { value: "SOM", option: "SOMALIA" },
  { value: "ZAF", option: "SOUTH AFRICA" },
  { value: "SGS", option: "SOUTH GEORGIA & THE SOUTH SANDWICH IS" },
  { value: "ESP", option: "SPAIN" },
  { value: "LKA", option: "SRI LANKA" },
  { value: "ZZA", option: "STATELESS" },
  { value: "XXA", option: "STATELESS PERSON ARTICLE 1/1954" },
  { value: "SDN", option: "SUDAN" },
  { value: "SUR", option: "SURIoption" },
  { value: "SJM", option: "SVALBARD AND JAN MAYEN ISLANDS" },
  { value: "SWZ", option: "SWAZILAND" },
  { value: "SWE", option: "SWEDEN" },
  { value: "CHE", option: "SWITZERLAND" },
  { value: "SYR", option: "SYRIA" },
  { value: "TWN", option: "TAIWAN" },
  { value: "TJK", option: "TAJIKISTAN" },
  { value: "TZA", option: "TANZANIA" },
  { value: "THA", option: "THAILAND" },
  { value: "FYR", option: "THE FORMER YUGOSLAV REP. OF MACEDONIA" },
  { value: "ZZB", option: "TIDAK DINYATAKAN OLEH KLN" },
  { value: "TLS", option: "TIMOR LESTE" },
  { value: "TMP", option: "TIMOR LESTE" },
  { value: "TGO", option: "TOGO" },
  { value: "TKL", option: "TOKELAU" },
  { value: "TON", option: "TONGA" },
  { value: "TTO", option: "TRINIDAD AND TOBAGO" },
  { value: "TUN", option: "TUNISIA" },
  { value: "TUR", option: "TURKEY" },
  { value: "TKM", option: "TURKMENISTAN" },
  { value: "TCA", option: "TURKS AND CAICOS ISLANDS" },
  { value: "TUV", option: "TUVALU" },
  { value: "UGA", option: "UGANDA" },
  { value: "GBD", option: "UK-DEPENDENT" },
  { value: "UKR", option: "UKRAINE" },
  { value: "UNA", option: "UN SPECIALIZED AGENCY" },
  { value: "UNH", option: "UNHCR" },
  { value: "ARE", option: "UNITED ARAB EMIRATES" },
  { value: "GBR", option: "UNITED KINGDOM" },
  { value: "UNO", option: "UNITED NATIONS ORGANIZATION" },
  { value: "UMI", option: "UNITED STATES MINOR OUTLYING ISLANDS" },
  { value: "ZZZ", option: "UNKNOWN" },
  { value: "ESH", option: "UNKNOWN / UNSPECIFIED NATIONALITY" },
  { value: "XXX", option: "UNSPECIFIED NATIONALITY" },
  { value: "URY", option: "URUGUAY" },
  { value: "USA", option: "USA" },
  { value: "UZB", option: "UZBEKISTAN" },
  { value: "VUT", option: "VANUATU" },
  { value: "VEN", option: "VENEZUELA" },
  { value: "VNM", option: "VIETNAM" },
  { value: "VGB", option: "VIRGIN ISLANDS (BRITISH)" },
  { value: "VIR", option: "VIRGIN ISLANDS (USA)" },
  { value: "WLF", option: "WALLIS AND FUTURA ISLANDS" },
  { value: "YEM", option: "YEMEN" },
  { value: "YUG", option: "YUGOSLAVIA" },
  { value: "ZAR", option: "ZAIRE" },
  { value: "ZMB", option: "ZAMBIA" },
  { value: "ZWE", option: "ZIMBABWE" },
  { value: "ZIM", option: "ZIMBABWE" }
];

const sex = [
    {value : 1, option : MALE},
    {value : 2, option : FEMALE},
]

const region = [
  { value: "1", option: "CANADA" },
  { value: "1", option: "UNITED STATES" },
  { value: "1242", option: "BAHAMAS" },
  { value: "1246", option: "BARBADOS" },
  { value: "1264", option: "ANGUILLA" },
  { value: "1268", option: "ANTIGUA AND BARBUDA" },
  { value: "1284", option: "BRITISH VIRGIN ISLANDS" },
  { value: "1340", option: "U.S. VIRGIN ISLANDS" },
  { value: "1345", option: "CAYMAN ISLANDS" },
  { value: "1441", option: "BERMUDA" },
  { value: "1473", option: "GRENADA" },
  { value: "1649", option: "TURKS AND CAICOS ISLANDS" },
  { value: "1664", option: "MONTSERRAT" },
  { value: "1670", option: "NORTHERN MARIANA ISLANDS" },
  { value: "1671", option: "GUAM" },
  { value: "1684", option: "AMERICAN SAMOA" },
  { value: "1721", option: "SINT MAARTEN" },
  { value: "1758", option: "SAINT LUCIA" },
  { value: "1767", option: "DOMINICA" },
  { value: "1784", option: "SAINT VINCENT AND THE GRENADINES" },
  { value: "1787", option: "PUERTO RICO" },
  { value: "1809", option: "DOMINICAN REPUBLIC" },
  { value: "1829", option: "DOMINICAN REPUBLIC" },
  { value: "1849", option: "DOMINICAN REPUBLIC" },
  { value: "1868", option: "TRINIDAD AND TOBAGO" },
  { value: "1869", option: "SAINT KITTS AND NEVIS" },
  { value: "1876", option: "JAMAICA" },
  { value: "1939", option: "PUERTO RICO" },
  { value: "20", option: "EGYPT" },
  { value: "211", option: "SOUTH SUDAN" },
  { value: "", option: "UNKNOWN / UNSPECIFIED NATIONALITY" },
  { value: "212", option: "MOROCCO" },
  { value: "213", option: "ALGERIA" },
  { value: "216", option: "TUNISIA" },
  { value: "218", option: "LIBYA" },
  { value: "220", option: "GAMBIA" },
  { value: "221", option: "SENEGAL" },
  { value: "222", option: "MAURITANIA" },
  { value: "223", option: "MALI" },
  { value: "224", option: "GUINEA" },
  { value: "225", option: "IVORY COAST" },
  { value: "226", option: "BURKINA FASO" },
  { value: "227", option: "NIGER" },
  { value: "228", option: "TOGO" },
  { value: "229", option: "BENIN" },
  { value: "230", option: "MAURITIUS" },
  { value: "231", option: "LIBERIA" },
  { value: "232", option: "SIERRA LEONE" },
  { value: "233", option: "GHANA" },
  { value: "234", option: "NIGERIA" },
  { value: "235", option: "CHAD" },
  { value: "236", option: "CENTRAL AFRICAN REPUBLIC" },
  { value: "237", option: "CAMEROON" },
  { value: "238", option: "CAPE VERDE" },
  { value: "239", option: "SAO TOME AND PRINCIPE" },
  { value: "240", option: "EQUATORIAL GUINEA" },
  { value: "241", option: "GABON" },
  { value: "242", option: "REPUBLIC OF THE CONGO" },
  { value: "243", option: "DEMOCRATIC REPUBLIC OF THE CONGO" },
  { value: "244", option: "ANGOLA" },
  { value: "245", option: "GUINEABISSAU" },
  { value: "246", option: "BRITISH INDIAN OCEAN TERRITORY" },
  { value: "248", option: "SEYCHELLES" },
  { value: "249", option: "SUDAN" },
  { value: "250", option: "RWANDA" },
  { value: "251", option: "ETHIOPIA" },
  { value: "252", option: "SOMALIA" },
  { value: "253", option: "DJIBOUTI" },
  { value: "254", option: "KENYA" },
  { value: "255", option: "TANZANIA" },
  { value: "256", option: "UGANDA" },
  { value: "257", option: "BURUNDI" },
  { value: "258", option: "MOZAMBIQUE" },
  { value: "260", option: "ZAMBIA" },
  { value: "261", option: "MADAGASCAR" },
  { value: "262", option: "MAYOTTE" },
  { value: "262", option: "REUNION" },
  { value: "263", option: "ZIMBABWE" },
  { value: "264", option: "NAMIBIA" },
  { value: "265", option: "MALAWI" },
  { value: "266", option: "LESOTHO" },
  { value: "267", option: "BOTSWANA" },
  { value: "268", option: "SWAZILAND" },
  { value: "269", option: "COMOROS" },
  { value: "27", option: "SOUTH AFRICA" },
  { value: "290", option: "SAINT HELENA" },
  { value: "291", option: "ERITREA" },
  { value: "297", option: "ARUBA" },
  { value: "298", option: "FAROE ISLANDS" },
  { value: "299", option: "GREENLAND" },
  { value: "30", option: "GREECE" },
  { value: "31", option: "NETHERLANDS" },
  { value: "32", option: "BELGIUM" },
  { value: "33", option: "FRANCE" },
  { value: "34", option: "SPAIN" },
  { value: "350", option: "GIBRALTAR" },
  { value: "351", option: "PORTUGAL" },
  { value: "352", option: "LUXEMBOURG" },
  { value: "353", option: "IRELAND" },
  { value: "354", option: "ICELAND" },
  { value: "355", option: "ALBANIA" },
  { value: "356", option: "MALTA" },
  { value: "357", option: "CYPRUS" },
  { value: "358", option: "FINLAND" },
  { value: "359", option: "BULGARIA" },
  { value: "36", option: "HUNGARY" },
  { value: "370", option: "LITHUANIA" },
  { value: "371", option: "LATVIA" },
  { value: "372", option: "ESTONIA" },
  { value: "373", option: "MOLDOVA" },
  { value: "374", option: "ARMENIA" },
  { value: "375", option: "BELARUS" },
  { value: "376", option: "ANDORRA" },
  { value: "377", option: "MONACO" },
  { value: "378", option: "SAN MARINO" },
  { value: "379", option: "VATICAN" },
  { value: "380", option: "UKRAINE" },
  { value: "381", option: "SERBIA" },
  { value: "382", option: "MONTENEGRO" },
  { value: "383", option: "KOSOVO" },
  { value: "385", option: "CROATIA" },
  { value: "386", option: "SLOVENIA" },
  { value: "387", option: "BOSNIA AND HERZEGOVINA" },
  { value: "389", option: "MACEDONIA" },
  { value: "39", option: "ITALY" },
  { value: "40", option: "ROMANIA" },
  { value: "41", option: "SWITZERLAND" },
  { value: "420", option: "CZECH REPUBLIC" },
  { value: "421", option: "SLOVAKIA" },
  { value: "423", option: "LIECHTENSTEIN" },
  { value: "43", option: "AUSTRIA" },
  { value: "44", option: "UNITED KINGDOM" },
  { value: "441481", option: "GUERNSEY" },
  { value: "441534", option: "JERSEY" },
  { value: "441624", option: "ISLE OF MAN" },
  { value: "45", option: "DENMARK" },
  { value: "46", option: "SWEDEN" },
  { value: "47", option: "NORWAY" },
  { value: "47", option: "SVALBARD AND JAN MAYEN" },
  { value: "48", option: "POLAND" },
  { value: "49", option: "GERMANY" },
  { value: "500", option: "FALKLAND ISLANDS" },
  { value: "501", option: "BELIZE" },
  { value: "502", option: "GUATEMALA" },
  { value: "503", option: "EL SALVADOR" },
  { value: "504", option: "HONDURAS" },
  { value: "505", option: "NICARAGUA" },
  { value: "506", option: "COSTA RICA" },
  { value: "507", option: "PANAMA" },
  { value: "508", option: "SAINT PIERRE AND MIQUELON" },
  { value: "509", option: "HAITI" },
  { value: "51", option: "PERU" },
  { value: "52", option: "MEXICO" },
  { value: "53", option: "CUBA" },
  { value: "54", option: "ARGENTINA" },
  { value: "55", option: "BRAZIL" },
  { value: "56", option: "CHILE" },
  { value: "57", option: "COLOMBIA" },
  { value: "58", option: "VENEZUELA" },
  { value: "590", option: "SAINT BARTHELEMY" },
  { value: "590", option: "SAINT MARTIN" },
  { value: "591", option: "BOLIVIA" },
  { value: "592", option: "GUYANA" },
  { value: "593", option: "ECUADOR" },
  { value: "595", option: "PARAGUAY" },
  { value: "597", option: "SURIoption" },
  { value: "598", option: "URUGUAY" },
  { value: "599", option: "NETHERLANDS ANTILLES" },
  { value: "599", option: "CURACAO" },
  { value: "60", option: "MALAYSIA" },
  { value: "61", option: "AUSTRALIA" },
  { value: "61", option: "COCOS ISLANDS" },
  { value: "61", option: "CHRISTMAS ISLAND" },
  { value: "62", option: "INDONESIA" },
  { value: "63", option: "PHILIPPINES" },
  { value: "64", option: "NEW ZEALAND" },
  { value: "64", option: "PITCAIRN" },
  { value: "65", option: "SINGAPORE" },
  { value: "66", option: "THAILAND" },
  { value: "670", option: "EAST TIMOR" },
  { value: "672", option: "ANTARCTICA" },
  { value: "673", option: "BRUNEI" },
  { value: "674", option: "NAURU" },
  { value: "675", option: "PAPUA NEW GUINEA" },
  { value: "676", option: "TONGA" },
  { value: "677", option: "SOLOMON ISLANDS" },
  { value: "678", option: "VANUATU" },
  { value: "679", option: "FIJI" },
  { value: "680", option: "PALAU" },
  { value: "681", option: "WALLIS AND FUTUNA" },
  { value: "682", option: "COOK ISLANDS" },
  { value: "683", option: "NIUE" },
  { value: "685", option: "SAMOA" },
  { value: "686", option: "KIRIBATI" },
  { value: "687", option: "NEW CALEDONIA" },
  { value: "688", option: "TUVALU" },
  { value: "689", option: "FRENCH POLYNESIA" },
  { value: "690", option: "TOKELAU" },
  { value: "691", option: "MICRONESIA" },
  { value: "692", option: "MARSHALL ISLANDS" },
  { value: "7", option: "KAZAKHSTAN" },
  { value: "7", option: "RUSSIA" },
  { value: "81", option: "JAPAN" },
  { value: "82", option: "SOUTH KOREA" },
  { value: "84", option: "VIETNAM" },
  { value: "850", option: "NORTH KOREA" },
  { value: "852", option: "HONG KONG" },
  { value: "853", option: "MACAU" },
  { value: "855", option: "CAMBODIA" },
  { value: "856", option: "LAOS" },
  { value: "86", option: "CHINA" },
  { value: "880", option: "BANGLADESH" },
  { value: "886", option: "TAIWAN" },
  { value: "90", option: "TURKEY" },
  { value: "91", option: "INDIA" },
  { value: "92", option: "PAKISTAN" },
  { value: "93", option: "AFGHANISTAN" },
  { value: "94", option: "SRI LANKA" },
  { value: "95", option: "MYANMAR" },
  { value: "960", option: "MALDIVES" },
  { value: "961", option: "LEBANON" },
  { value: "962", option: "JORDAN" },
  { value: "963", option: "SYRIA" },
  { value: "964", option: "IRAQ" },
  { value: "965", option: "KUWAIT" },
  { value: "966", option: "SAUDI ARABIA" },
  { value: "967", option: "YEMEN" },
  { value: "968", option: "OMAN" },
  { value: "970", option: "PALESTINE" },
  { value: "971", option: "UNITED ARAB EMIRATES" },
  { value: "972", option: "ISRAEL" },
  { value: "973", option: "BAHRAIN" },
  { value: "974", option: "QATAR" },
  { value: "975", option: "BHUTAN" },
  { value: "976", option: "MONGOLIA" },
  { value: "977", option: "NEPAL" },
  { value: "98", option: "IRAN" },
  { value: "992", option: "TAJIKISTAN" },
  { value: "993", option: "TURKMENISTAN" },
  { value: "994", option: "AZERBAIJAN" },
  { value: "995", option: "GEORGIA" },
  { value: "996", option: "KYRGYZSTAN" },
  { value: "998", option: "UZBEKISTAN" }
];

const modeofTravel = [
    {option : 1, value : AIR},
    {option : 2, value : LAND},
    {option : 3, value : SEA},
]

const embark = [
  { value: "AFG", option: "AFGHANISTAN" },
  { value: "ALB", option: "ALBANIA" },
  { value: "DZA", option: "ALGERIA" },
  { value: "ASM", option: "AMERICAN SAMOA" },
  { value: "AND", option: "ANDORRA" },
  { value: "AGO", option: "ANGOLA" },
  { value: "AIA", option: "ANGUILLA" },
  { value: "ATA", option: "ANTARCTICA" },
  { value: "ATG", option: "ANTIGUA AND BARBUDA" },
  { value: "ARG", option: "ARGENTINA" },
  { value: "ARM", option: "ARMENIA" },
  { value: "ABW", option: "ARUBA" },
  { value: "AUS", option: "AUSTRALIA" },
  { value: "AUT", option: "AUSTRIA" },
  { value: "AZE", option: "AZERBAIJAN" },
  { value: "BHS", option: "BAHAMAS" },
  { value: "BHR", option: "BAHRAIN" },
  { value: "BGD", option: "BANGLADESH" },
  { value: "BRB", option: "BARBADOS" },
  { value: "BLR", option: "BELARUS" },
  { value: "BEL", option: "BELGIUM" },
  { value: "BLZ", option: "BELIZE" },
  { value: "BEN", option: "BENIN" },
  { value: "BMU", option: "BERMUDA" },
  { value: "BTN", option: "BHUTAN" },
  { value: "BOL", option: "BOLIVIA" },
  { value: "BIH", option: "BOSNIA AND HERZEGOVINA" },
  { value: "BWA", option: "BOTSWANA" },
  { value: "BVT", option: "BOUVET ISLAND" },
  { value: "BRA", option: "BRAZIL" },
  { value: "IOT", option: "BRITISH INDIAN OCEAN TERRITORY" },
  { value: "GBN", option: "BRITISH NATIONAL OVERSEAS" },
  { value: "GBO", option: "BRITISH OVERSEAS CITIZENS" },
  { value: "GBP", option: "BRITISH PROTECTED PERSON" },
  { value: "GBS", option: "BRITISH SUBJECT" },
  { value: "BRN", option: "BRUNEI DARUSSALAM" },
  { value: "BGR", option: "BULGARIA" },
  { value: "BFA", option: "BURKINA FASO" },
  { value: "BDI", option: "BURUNDI" },
  { value: "KHM", option: "CAMBODIA" },
  { value: "CMR", option: "CAMEROON" },
  { value: "CAN", option: "CANADA" },
  { value: "CPV", option: "CAPE VERDE" },
  { value: "CYM", option: "CAYMAN ISLANDS" },
  { value: "CAF", option: "CENTRAL AFRICAN REPUBLIC" },
  { value: "TCD", option: "CHAD" },
  { value: "CHL", option: "CHILE" },
  { value: "CHN", option: "CHINA" },
  { value: "CXR", option: "CHRISTMAS ISLAND" },
  { value: "CCK", option: "COCOS ISLANDS" },
  { value: "COL", option: "COLOMBIA" },
  { value: "COM", option: "COMOROS" },
  { value: "COG", option: "CONGO" },
  { value: "COK", option: "COOK ISLANDS" },
  { value: "CRI", option: "COSTA RICA" },
  { value: "CIV", option: "COTE D'IVOIRE" },
  { value: "HRV", option: "CROATIA" },
  { value: "CUB", option: "CUBA" },
  { value: "CYP", option: "CYPRUS" },
  { value: "CZE", option: "CZECH REPUBLIC" },
  { value: "PRK", option: "DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA" },
  { value: "DPR", option: "DEMOCRATIC PEOPLES REPUBLIC OF KOREA" },
  { value: "COD", option: "DEMOCRATIC REPUBLIC OF THE CONGO" },
  { value: "DNK", option: "DENMARK" },
  { value: "DJI", option: "DJIBOUTI" },
  { value: "DMA", option: "DOMINICA" },
  { value: "DOM", option: "DOMINICAN REPUBLIC" },
  { value: "ECU", option: "ECUADOR" },
  { value: "EGY", option: "EGYPT" },
  { value: "SLV", option: "EL SALVADOR" },
  { value: "GNQ", option: "EQUATORIAL GUINEA" },
  { value: "ERI", option: "ERITREA" },
  { value: "EST", option: "ESTONIA" },
  { value: "ETH", option: "ETHIOPIA" },
  { value: "EUE", option: "EUROPEAN UNION LAISSER PASSER" },
  { value: "FLK", option: "FALKLAND ISLAND (MALVINAS)" },
  { value: "FRO", option: "FAROE ISLANDS" },
  { value: "FJI", option: "FIJI" },
  { value: "FIN", option: "FINLAND" },
  { value: "FXX", option: "FINLAND, METROPOLITAN" },
  { value: "FRA", option: "FRANCE" },
  { value: "GUF", option: "FRENCH GUIANA" },
  { value: "PYF", option: "FRENCH POLYNESIA" },
  { value: "ATF", option: "FRENCH SOUTHERN TERRITORIES" },
  { value: "GAB", option: "GABON" },
  { value: "GMB", option: "GAMBIA" },
  { value: "GEO", option: "GEORGIA" },
  { value: "DGR", option: "GERMANY" },
  { value: "DEU", option: "GERMANY" },
  { value: "GHA", option: "GHANA" },
  { value: "GIB", option: "GIBRALTAR" },
  { value: "GRC", option: "GREECE" },
  { value: "GRL", option: "GREENLAND" },
  { value: "GRD", option: "GRENADA" },
  { value: "GLP", option: "GUADELOUPE" },
  { value: "GUM", option: "GUAM" },
  { value: "GTM", option: "GUATEMALA" },
  { value: "GNB", option: "GUIENA-BISSAU" },
  { value: "GIN", option: "GUINEA" },
  { value: "GUY", option: "GUYANA" },
  { value: "HTI", option: "HAITI" },
  { value: "HMD", option: "HEARD AND MCDONALD ISLANDS" },
  { value: "VAT", option: "HOLY SEE (VATICAN CITY STATE)" },
  { value: "HND", option: "HONDURAS" },
  { value: "HKG", option: "HONG KONG" },
  { value: "HUN", option: "HUNGARY" },
  { value: "ISL", option: "ICELAND" },
  { value: "IND", option: "INDIA" },
  { value: "IDN", option: "INDONESIA" },
  { value: "IRN", option: "IRAN" },
  { value: "IRQ", option: "IRAQ" },
  { value: "IRL", option: "IRELAND" },
  { value: "ISR", option: "ISRAEL" },
  { value: "ITA", option: "ITALY" },
  { value: "JAM", option: "JAMAICA" },
  { value: "JPN", option: "JAPAN" },
  { value: "JOR", option: "JORDAN" },
  { value: "KAZ", option: "KAZAKHSTAN" },
  { value: "KEN", option: "KENYA" },
  { value: "KIR", option: "KIRIBATI" },
  { value: "KWT", option: "KUWAIT" },
  { value: "KGZ", option: "KYRGYZSTAN" },
  { value: "LAO", option: "LAO PDR" },
  { value: "LVA", option: "LATVIA" },
  { value: "LBN", option: "LEBANON" },
  { value: "LSO", option: "LESOTHO" },
  { value: "LBR", option: "LIBERIA" },
  { value: "LBY", option: "LIBYA" },
  { value: "LIE", option: "LIECHTENSTEIN" },
  { value: "LTU", option: "LITHUANIA" },
  { value: "LUX", option: "LUXEMBOURG" },
  { value: "MAC", option: "MACAU" },
  { value: "MDG", option: "MADAGASCAR" },
  { value: "MWI", option: "MALAWI" },
  { value: "MYS", option: "MALAYSIA" },
  { value: "MDV", option: "MALDIVES" },
  { value: "MLI", option: "MALI" },
  { value: "MLT", option: "MALTA" },
  { value: "MHL", option: "MARSHALL ISLANDS" },
  { value: "MTQ", option: "MARTINIQUE" },
  { value: "MRT", option: "MAURITANIA" },
  { value: "MUS", option: "MAURITIUS" },
  { value: "MYT", option: "MAYOTTE" },
  { value: "MEX", option: "MEXICO" },
  { value: "FSM", option: "MICRONESIA,FEDERATED STATES OF" },
  { value: "MCO", option: "MONACO" },
  { value: "MNG", option: "MONGOLIA" },
  { value: "MNE", option: "MONTENEGRO" },
  { value: "MSR", option: "MONTSERRAT" },
  { value: "MAR", option: "MOROCCO" },
  { value: "MOZ", option: "MOZAMBIQUE" },
  { value: "MMR", option: "MYANMAR" },
  { value: "NAM", option: "NAMIBIA" },
  { value: "NRU", option: "NAURU" },
  { value: "NNS", option: "NEGARA-NEGARA SUMBER" },
  { value: "NPL", option: "NEPAL" },
  { value: "NLD", option: "NETHERLANDS" },
  { value: "ANT", option: "NETHERLANDS ANTILLES" },
  { value: "NTZ", option: "NEUTRAL ZONE" },
  { value: "NCL", option: "NEW CELEDONIA" },
  { value: "NZL", option: "NEW ZEALAND" },
  { value: "NIC", option: "NICARAGUA" },
  { value: "NER", option: "NIGER" },
  { value: "NGA", option: "NIGERIA" },
  { value: "ZZD", option: "NIL" },
  { value: "NIU", option: "NIUE" },
  { value: "NFK", option: "NORFOLK ISLAND" },
  { value: "MNP", option: "NORTHERN MARIANA ISLANDS" },
  { value: "NOR", option: "NORWAY" },
  { value: "OMN", option: "OMAN" },
  { value: "PAK", option: "PAKISTAN" },
  { value: "PLW", option: "PALAU" },
  { value: "PAL", option: "PALESTINE" },
  { value: "PSE", option: "PALESTINE" },
  { value: "PAN", option: "PANAMA" },
  { value: "PNG", option: "PAPUA NEW GUINEA" },
  { value: "PRY", option: "PARAGUAY" },
  { value: "PER", option: "PERU" },
  { value: "PHL", option: "PHILIPPINES" },
  { value: "PCN", option: "PITCAIRN ISLAND" },
  { value: "POL", option: "POLAND" },
  { value: "PRT", option: "PORTUGAL" },
  { value: "PRI", option: "PUERTO RICO" },
  { value: "QAT", option: "QATAR" },
  { value: "XXC", option: "REFUGEE" },
  { value: "XXB", option: "REFUGEE ARTICLE 1/1951" },
  { value: "MDA", option: "REP OF MOLDOVA" },
  { value: "RKS", option: "REP. KOSOVO" },
  { value: "KOR", option: "REPUBLIC OF KOREA" },
  { value: "KOS", option: "REPUBLIC OF KOSOVO" },
  { value: "MKD", option: "REPUBLIC OF MACEDONIA" },
  { value: "ROS", option: "REPUBLIC OF SOMALILAND" },
  { value: "SSD", option: "REPUBLIC OF SOUTH SUDAN" },
  { value: "REU", option: "REUNION" },
  { value: "ROM", option: "ROMANIA" },
  { value: "ROU", option: "ROMANIA" },
  { value: "RUS", option: "RUSSIA" },
  { value: "RWA", option: "RWANDA" },
  { value: "SHN", option: "SAINT HELENA" },
  { value: "KNA", option: "SAINT KITTS AND NEVIS" },
  { value: "LCA", option: "SAINT LUCIA" },
  { value: "SPM", option: "SAINT PIERRE AND MIQUELON" },
  { value: "VCT", option: "SAINT VINCENT AND THE GRENADINES" },
  { value: "WSM", option: "SAMOA" },
  { value: "SMR", option: "SAN MARINO" },
  { value: "STP", option: "SAO TOME AND PRINCIPE" },
  { value: "SAU", option: "SAUDI ARABIA" },
  { value: "SEN", option: "SENEGAL" },
  { value: "SER", option: "SERBIA" },
  { value: "SRB", option: "SERBIA" },
  { value: "SCG", option: "SERBIA AND MONTENEGRO" },
  { value: "SYC", option: "SEYCHELLES" },
  { value: "SLE", option: "SIERRA LEONE" },
  { value: "SGP", option: "SINGAPORE" },
  { value: "SVK", option: "SLOVAKIA" },
  { value: "SVN", option: "SLOVENIA" },
  { value: "SLB", option: "SOLOMON ISLANDS" },
  { value: "SOM", option: "SOMALIA" },
  { value: "ZAF", option: "SOUTH AFRICA" },
  { value: "SGS", option: "SOUTH GEORGIA & THE SOUTH SANDWICH IS" },
  { value: "ESP", option: "SPAIN" },
  { value: "LKA", option: "SRI LANKA" },
  { value: "ZZA", option: "STATELESS" },
  { value: "XXA", option: "STATELESS PERSON ARTICLE 1/1954" },
  { value: "SDN", option: "SUDAN" },
  { value: "SUR", option: "SURIoption" },
  { value: "SJM", option: "SVALBARD AND JAN MAYEN ISLANDS" },
  { value: "SWZ", option: "SWAZILAND" },
  { value: "SWE", option: "SWEDEN" },
  { value: "CHE", option: "SWITZERLAND" },
  { value: "SYR", option: "SYRIA" },
  { value: "TWN", option: "TAIWAN" },
  { value: "TJK", option: "TAJIKISTAN" },
  { value: "TZA", option: "TANZANIA" },
  { value: "THA", option: "THAILAND" },
  { value: "FYR", option: "THE FORMER YUGOSLAV REP. OF MACEDONIA" },
  { value: "ZZB", option: "TIDAK DINYATAKAN OLEH KLN" },
  { value: "TLS", option: "TIMOR LESTE" },
  { value: "TMP", option: "TIMOR LESTE" },
  { value: "TGO", option: "TOGO" },
  { value: "TKL", option: "TOKELAU" },
  { value: "TON", option: "TONGA" },
  { value: "TTO", option: "TRINIDAD AND TOBAGO" },
  { value: "TUN", option: "TUNISIA" },
  { value: "TUR", option: "TURKEY" },
  { value: "TKM", option: "TURKMENISTAN" },
  { value: "TCA", option: "TURKS AND CAICOS ISLANDS" },
  { value: "TUV", option: "TUVALU" },
  { value: "UGA", option: "UGANDA" },
  { value: "GBD", option: "UK-DEPENDENT" },
  { value: "UKR", option: "UKRAINE" },
  { value: "UNA", option: "UN SPECIALIZED AGENCY" },
  { value: "UNH", option: "UNHCR" },
  { value: "ARE", option: "UNITED ARAB EMIRATES" },
  { value: "GBR", option: "UNITED KINGDOM" },
  { value: "UNO", option: "UNITED NATIONS ORGANIZATION" },
  { value: "UMI", option: "UNITED STATES MINOR OUTLYING ISLANDS" },
  { value: "ZZZ", option: "UNKNOWN" },
  { value: "ESH", option: "UNKNOWN / UNSPECIFIED NATIONALITY" },
  { value: "XXX", option: "UNSPECIFIED NATIONALITY" },
  { value: "URY", option: "URUGUAY" },
  { value: "USA", option: "USA" },
  { value: "UZB", option: "UZBEKISTAN" },
  { value: "VUT", option: "VANUATU" },
  { value: "VEN", option: "VENEZUELA" },
  { value: "VNM", option: "VIETNAM" },
  { value: "VGB", option: "VIRGIN ISLANDS (BRITISH)" },
  { value: "VIR", option: "VIRGIN ISLANDS (USA)" },
  { value: "WLF", option: "WALLIS AND FUTURA ISLANDS" },
  { value: "YEM", option: "YEMEN" },
  { value: "YUG", option: "YUGOSLAVIA" },
  { value: "ZAR", option: "ZAIRE" },
  { value: "ZMB", option: "ZAMBIA" },
  { value: "ZWE", option: "ZIMBABWE" },
  { value: "ZIM", option: "ZIMBABWE" }
];

const accomoDation = [
    {option : "HOTEL/MOTEL/REST HOUSE", value : "01"},
    {option : "RESIDENCE OF FRIENDS/RELATIVES", value : "02"},
    {option : "OTHERS", value : "03"}
]

const state = [
  { value: "", option: "Please Choose" },
  { value: "01", option: "JOHOR" },
  { value: "02", option: "KEDAH" },
  { value: "03", option: "KELANTAN" },
  { value: "04", option: "MELAKA" },
  { value: "05", option: "NEGERI SEMBILAN" },
  { value: "06", option: "PAHANG" },
  { value: "07", option: "PULAU PINANG" },
  { value: "08", option: "PERAK" },
  { value: "09", option: "PERLIS" },
  { value: "10", option: "SELANGOR" },
  { value: "11", option: "TERENGGANU" },
  { value: "12", option: "SABAH" },
  { value: "13", option: "SARAWAK" },
  { value: "14", option: "WP KUALA LUMPUR" },
  { value: "15", option: "WP LABUAN" },
  { value: "16", option: "WP PUTRAJAYA" }
];

const JOHOR = [
  { value: "0100", option: "JOHOR" },
  { value: "0101", option: "ASAHAN" },
  { value: "0102", option: "AYER BALOI" },
  { value: "0103", option: "AYER HITAM" },
  { value: "0104", option: "BAKRI" },
  { value: "0105", option: "BATU ANAM" },
  { value: "0106", option: "BATU PAHAT" },
  { value: "0107", option: "BEKOK" },
  { value: "0108", option: "BENUT" },
  { value: "0109", option: "BUKIT GAMBIR" },
  { value: "0110", option: "BUKIT PASIR" },
  { value: "0111", option: "CHAAH" },
  { value: "0112", option: "ENDAU" },
  { value: "0113", option: "GELANG PATAH" },
  { value: "0114", option: "GEMAS" },
  { value: "0115", option: "GERSEK" },
  { value: "0116", option: "G. TAIB ANDAK" },
  { value: "0117", option: "JEMENTAH" },
  { value: "0118", option: "JOHOR BAHRU" },
  { value: "0119", option: "KAHANG" },
  { value: "0120", option: "KLUANG" },
  { value: "0121", option: "KG KNGAN T DR" },
  { value: "0122", option: "KOTA TINGGI" },
  { value: "0123", option: "KUKUP" },
  { value: "0124", option: "KULAI" },
  { value: "0125", option: "LABIS" },
  { value: "0126", option: "LAYANG-LAYANG" },
  { value: "0127", option: "MASAI" },
  { value: "0128", option: "MERSING" },
  { value: "0129", option: "MUAR" },
  { value: "0130", option: "PAGOH" },
  { value: "0131", option: "PALOH" },
  { value: "0132", option: "PANCHOR" },
  { value: "0133", option: "PARIT JAWA" },
  { value: "0134", option: "PARIT RAJA" },
  { value: "0135", option: "PARIT SULONG" },
  { value: "0136", option: "PASIR GUDANG" },
  { value: "0137", option: "PEKAN NANAS" },
  { value: "0138", option: "PENGERANG" },
  { value: "0139", option: "PONTIAN" },
  { value: "0140", option: "RENGIT" },
  { value: "0141", option: "SEGAMAT" },
  { value: "0142", option: "SKUDAI" },
  { value: "0143", option: "SEMERAH" },
  { value: "0144", option: "SENAI" },
  { value: "0145", option: "SENGGARANG" },
  { value: "0146", option: "SIMPANG RENGGAM" },
  { value: "0147", option: "SUNGAI MATI" },
  { value: "0148", option: "TANGKAK" },
  { value: "0149", option: "ULU TIRAM" },
  { value: "0150", option: "YONG PENG" },
  { value: "0151", option: "SAGIL" },
  { value: "0157", option: "BUKIT KEPONG" },
  { value: "0177", option: "LENGA" },
  { value: "0191", option: "SUNGAI BALANG" },
  { value: "0192", option: "GEMAS BARU" },
  { value: "0193", option: "RENGGAM" },
  { value: "0194", option: "BANDAR PENAWAR" },
  { value: "0195", option: "LEDANG" },
  { value: "0196", option: "ISKANDAR PUTERI" },
  { value: "0197", option: "KULAI JAYA" },
  { value: "0198", option: "KANGKAR PULAI" }
];

const KEDAH = [
  { value: "0200", option: "KEDAH" },
  { value: "0201", option: "ALOR SETAR" },
  { value: "0202", option: "BALING" },
  { value: "0203", option: "BANDAR BAHARU" },
  { value: "0204", option: "BEDONG" },
  { value: "0205", option: "GURUN" },
  { value: "0206", option: "JITRA" },
  { value: "0207", option: "KARANGAN" },
  { value: "0208", option: "KEPALA BATAS" },
  { value: "0209", option: "KODIANG" },
  { value: "0210", option: "KOTA KUALA MUDA" },
  { value: "0211", option: "KUALA KEDAH" },
  { value: "0212", option: "KUALA KETIL" },
  { value: "0213", option: "KUALA NERANG" },
  { value: "0214", option: "KULIM" },
  { value: "0215", option: "KUPANG" },
  { value: "0216", option: "LANGGAR" },
  { value: "0217", option: "LANGKAWI" },
  { value: "0218", option: "LUNAS" },
  { value: "0219", option: "MERBOK" },
  { value: "0220", option: "PADANG SERAI" },
  { value: "0221", option: "PENDANG" },
  { value: "0222", option: "POKOK SENA" },
  { value: "0223", option: "SERDANG" },
  { value: "0224", option: "SIK" },
  { value: "0225", option: "SUNGAI PETANI" },
  { value: "0226", option: "YAN" },
  { value: "0234", option: "CHANGLOON" },
  { value: "0235", option: "SINTOK" },
  { value: "0281", option: "SG. BAKAP" },
  { value: "0282", option: "BUKIT KAYU HITAM" },
  { value: "0284", option: "SIMPANG EMPAT" },
  { value: "0285", option: "KOTA SARANG SEMUT" },
  { value: "0286", option: "JENIANG" },
  { value: "0287", option: "SINTOK" }
];

const KELANTAN = [
  { value: "0300", option: "KELANTAN" },
  { value: "0301", option: "AYER LANAS" },
  { value: "0302", option: "BACHOK" },
  { value: "0303", option: "CHERANG RUKU" },
  { value: "0304", option: "DABONG" },
  { value: "0305", option: "GUA MUSANG" },
  { value: "0306", option: "JELI" },
  { value: "0307", option: "K DESA PAHLAWAN" },
  { value: "0308", option: "KETEREH" },
  { value: "0309", option: "KOTA BHARU" },
  { value: "0310", option: "KUALA KRAI" },
  { value: "0311", option: "MACHANG" },
  { value: "0312", option: "MELOR" },
  { value: "0313", option: "PASIR MAS" },
  { value: "0314", option: "PASIR PUTEH" },
  { value: "0315", option: "PULAI CHONDONG" },
  { value: "0316", option: "RANTAU PANJANG" },
  { value: "0317", option: "TANAH MERAH" },
  { value: "0318", option: "TEMANGAN" },
  { value: "0319", option: "TUMPAT" },
  { value: "0320", option: "WAKAF BHARU" },
  { value: "0321", option: "SELISING" },
  { value: "0322", option: "KUALA BALAH" }
];

const MELAKA = [
  { value: "0400", option: "MELAKA" },
  { value: "0401", option: "ALOR GAJAH" },
  { value: "0402", option: "ASAHAN" },
  { value: "0403", option: "BATANG MELAKA" },
  { value: "0404", option: "BEMBAN" },
  { value: "0405", option: "DURIAN TUNGGAL" },
  { value: "0406", option: "GEMAS" },
  { value: "0407", option: "JASIN" },
  { value: "0408", option: "K/SUNGAI BARU" },
  { value: "0409", option: "LUBOK CHINA" },
  { value: "0410", option: "MASJID TANAH" },
  { value: "0411", option: "MELAKA" },
  { value: "0412", option: "MERLIMAU" },
  { value: "0413", option: "SUNGAI RAMBAI" },
  { value: "0414", option: "SUNGAI UDANG" },
  { value: "0415", option: "TAMPIN" },
  { value: "0416", option: "TANJONG KELING" },
  { value: "0417", option: "SELANDAR" },
  { value: "0418", option: "BUKIT KATIL" },
  { value: "0419", option: "AYER KEROH" },
  { value: "0420", option: "BATU BERENDAM" }
];

const NEGERI_SEMBILAN = [
  { value: "0500", option: "N SEMBILAN" },
  { value: "0501", option: "ASAHAN" },
  { value: "0502", option: "BAHAU" },
  { value: "0503", option: "BATANG MELAKA" },
  { value: "0504", option: "BATU KIKIR" },
  { value: "0505", option: "DURIAN TIPUS" },
  { value: "0506", option: "GEMAS" },
  { value: "0507", option: "GEMENCHEH" },
  { value: "0508", option: "JOHOL" },
  { value: "0509", option: "KOTA" },
  { value: "0510", option: "KUALA KLAWANG" },
  { value: "0511", option: "KUALA PILAH" },
  { value: "0512", option: "LABU" },
  { value: "0513", option: "LENGGENG" },
  { value: "0514", option: "LINGGI" },
  { value: "0515", option: "LUBOK CHINA" },
  { value: "0516", option: "MANTIN" },
  { value: "0517", option: "NILAI" },
  { value: "0518", option: "PASIR PANJANG" },
  { value: "0519", option: "PEDAS" },
  { value: "0520", option: "PORT DICKSON" },
  { value: "0521", option: "RANTAU" },
  { value: "0522", option: "REMBAU" },
  { value: "0523", option: "ROMPIN" },
  { value: "0524", option: "SELIAU" },
  { value: "0525", option: "SEREMBAN" },
  { value: "0526", option: "SRI MENANTI" },
  { value: "0527", option: "SI RUSA" },
  { value: "0528", option: "SILIAU" },
  { value: "0529", option: "SIMPANG PERTANG" },
  { value: "0530", option: "SUNGAI GADUT" },
  { value: "0531", option: "TAMPIN" },
  { value: "0532", option: "TANJUNG IPOH" },
  { value: "0533", option: "TITI" },
  { value: "0534", option: "BUKIT PELANDOK" },
  { value: "0535", option: "CHUAH" },
  { value: "0536", option: "LUKUT" },
  { value: "0537", option: "TELUK KEMANG" },
  { value: "0538", option: "PENG.KEMPAS" },
  { value: "0539", option: "JELEBU" },
  { value: "0540", option: "BANDAR SERI JEMPOL" },
  { value: "0541", option: "JUASSEH" },
  { value: "0542", option: "B BARU JEMPOL" },
  { value: "0543", option: "BANDAR ENSTEK" },
  { value: "0545", option: "PUSAT BANDAR PALONG" }
];

const PAHANG = [
  { value: "0600", option: "PAHANG" },
  { value: "0601", option: "BANDAR JENGKA" },
  { value: "0602", option: "BENTA" },
  { value: "0603", option: "BENTONG" },
  { value: "0604", option: "BESERAH" },
  { value: "0605", option: "BUKIT FRASER" },
  { value: "0606", option: "CHENOR" },
  { value: "0607", option: "DONG" },
  { value: "0608", option: "GAMBANG" },
  { value: "0609", option: "GENTING" },
  { value: "0610", option: "JERANTUT" },
  { value: "0611", option: "KARAK" },
  { value: "0612", option: "KEMAYAN" },
  { value: "0613", option: "KUALA LIPIS" },
  { value: "0614", option: "KUALA ROMPIN" },
  { value: "0615", option: "KUANTAN" },
  { value: "0616", option: "LANCHANG" },
  { value: "0617", option: "LURAH BILUT" },
  { value: "0618", option: "MARAN" },
  { value: "0619", option: "MENGKARAK" },
  { value: "0620", option: "MENTAKAB" },
  { value: "0621", option: "MERSING" },
  { value: "0622", option: "MUADZAM SHAH" },
  { value: "0623", option: "PADANG TENGKU" },
  { value: "0624", option: "PEKAN" },
  { value: "0625", option: "RAUB" },
  { value: "0626", option: "RINGLET" },
  { value: "0627", option: "SEGAMAT" },
  { value: "0628", option: "SUNGAI LEMBING" },
  { value: "0629", option: "SUNGAI RUAN" },
  { value: "0630", option: "TANAH RATA" },
  { value: "0631", option: "TEMERLOH" },
  { value: "0632", option: "TRIANG" },
  { value: "0633", option: "BDR TUN RAZAK" },
  { value: "0634", option: "ROMPIN" },
  { value: "0635", option: "C HIGHLANDS" },
  { value: "0636", option: "BANDAR BERA" },
  { value: "0637", option: "SEGA" },
  { value: "0639", option: "BRINCHANG" }
];

const PULAU_PINANG = [
  { value: "0700", option: "P PINANG" },
  { value: "0701", option: "AYER ITAM" },
  { value: "0702", option: "BALIK PULAU" },
  { value: "0703", option: "BATU FERRINGHI" },
  { value: "0704", option: "BAYAN LEPAS" },
  { value: "0705", option: "BUKIT MERTAJAM" },
  { value: "0706", option: "BUTTERWORTH" },
  { value: "0707", option: "GELUGOR" },
  { value: "0708", option: "GEORGETOWN" },
  { value: "0709", option: "KEPALA BATAS" },
  { value: "0710", option: "NIBONG TEBAL" },
  { value: "0711", option: "PENAGA" },
  { value: "0712", option: "PENANG HILL" },
  { value: "0713", option: "PERAI" },
  { value: "0714", option: "PERMATANG PAUH" },
  { value: "0715", option: "PULAU PINANG" },
  { value: "0716", option: "SIMPANG AMPAT" },
  { value: "0717", option: "SUNGAI JAWI" },
  { value: "0718", option: "TANJONG BUNGAH" },
  { value: "0719", option: "TASEK GELUGOR" },
  { value: "0720", option: "USM P/PINANG" },
  { value: "0721", option: "SUNGAI BAKAP" },
  { value: "0722", option: "JELUTONG" },
  { value: "0723", option: "MINDEN" },
  { value: "0724", option: "TANJONG TOKONG" },
  { value: "0725", option: "BAYAN BARU" }
];

const PERAK = [
  { value: "0800", option: "PERAK" },
  { value: "0801", option: "AYER TAWAR" },
  { value: "0802", option: "BAGAN DATOH" },
  { value: "0803", option: "BAGAN SERAI" },
  { value: "0804", option: "BATU GAJAH" },
  { value: "0805", option: "BATU KURAU" },
  { value: "0806", option: "BERUAS" },
  { value: "0807", option: "BIDOR" },
  { value: "0808", option: "BOTA" },
  { value: "0809", option: "CHKT KERUING" },
  { value: "0810", option: "CHEMOR" },
  { value: "0811", option: "CHENDERIANG" },
  { value: "0812", option: "CHENDERONG BALAI" },
  { value: "0813", option: "ENGGOR" },
  { value: "0814", option: "GERIK" },
  { value: "0815", option: "GOPENG" },
  { value: "0816", option: "HUTAN MELINTANG" },
  { value: "0817", option: "KLIAN INTAN" },
  { value: "0818", option: "IPOH" },
  { value: "0819", option: "KAMPAR" },
  { value: "0820", option: "KAMPONG GAJAH" },
  { value: "0821", option: "KG KEPAYANG" },
  { value: "0822", option: "KAMUNTING" },
  { value: "0823", option: "KUALA KANGSAR" },
  { value: "0824", option: "KUALA SEPETANG" },
  { value: "0825", option: "LAHAT" },
  { value: "0826", option: "LANGKAP" },
  { value: "0827", option: "LENGGONG" },
  { value: "0828", option: "LUMUT" },
  { value: "0829", option: "MALIM NAWAR" },
  { value: "0830", option: "MAMBANG DIAWAN" },
  { value: "0831", option: "MANONG" },
  { value: "0832", option: "MATANG" },
  { value: "0833", option: "MENGLEMBU" },
  { value: "0834", option: "PADANG RENGAS" },
  { value: "0835", option: "PANGKOR" },
  { value: "0836", option: "PANTAI REMIS" },
  { value: "0837", option: "PARIT" },
  { value: "0838", option: "PARIT BUNTAR" },
  { value: "0839", option: "PENGKALAN HULU" },
  { value: "0840", option: "PUSING" },
  { value: "0841", option: "SAUK" },
  { value: "0842", option: "SELAMA" },
  { value: "0843", option: "SELEKOH" },
  { value: "0844", option: "SEMANGGOL" },
  { value: "0845", option: "SIMPANG" },
  { value: "0846", option: "SIMPANG AMPAT" },
  { value: "0847", option: "SITIAWAN" },
  { value: "0848", option: "SLIM RIVER" },
  { value: "0849", option: "SUNGAI SIPUT" },
  { value: "0850", option: "SUNGAI SUMUN" },
  { value: "0851", option: "SUNGKAI" },
  { value: "0852", option: "TAIPING" },
  { value: "0853", option: "TANJUNG MALIM" },
  { value: "0854", option: "TG.PIANDANG" },
  { value: "0855", option: "TG.RAMBUTAN" },
  { value: "0856", option: "TANJONG TUALANG" },
  { value: "0857", option: "TAPAH" },
  { value: "0858", option: "TAPAH ROAD" },
  { value: "0859", option: "TELUK INTAN" },
  { value: "0860", option: "TEMOH" },
  { value: "0861", option: "TRONG" },
  { value: "0862", option: "TERONOH" },
  { value: "0863", option: "ULU KINTA" },
  { value: "0864", option: "ULU BERNAM" },
  { value: "0865", option: "SG SIPUT (U)" },
  { value: "0866", option: "BEHRANG STESEN" },
  { value: "0867", option: "TROLAK" },
  { value: "0880", option: "KUALA DIPANG" },
  { value: "0881", option: "KUALA KURAU" },
  { value: "0882", option: "SERI MANJUNG" },
  { value: "0886", option: "RANTAU PANJANG" },
  { value: "0887", option: "CHIKUS" }
];

const PERLIS = [
  { value: "0900", option: "PERLIS" },
  { value: "0901", option: "ARAU" },
  { value: "0902", option: "KAKI BUKIT" },
  { value: "0903", option: "KANGAR" },
  { value: "0904", option: "KUALA PERLIS" },
  { value: "0905", option: "PADANG BESAR" },
  { value: "0906", option: "SIMPANG AMPAT" }
];

const SELANGOR = [
  { value: "1000", option: "SELANGOR" },
  { value: "1001", option: "AMPANG" },
  { value: "1002", option: "BANTING" },
  { value: "1003", option: "BTG.BERJUNTAI" },
  { value: "1004", option: "BATANG KALI" },
  { value: "1005", option: "BATU 9 CHERAS" },
  { value: "1006", option: "BATU ARANG" },
  { value: "1007", option: "BATU CAVES" },
  { value: "1008", option: "BERANANG" },
  { value: "1009", option: "BUKIT ROTAN" },
  { value: "1010", option: "DENGKIL" },
  { value: "1011", option: "HULU LANGAT" },
  { value: "1012", option: "JENJAROM" },
  { value: "1013", option: "JERAM" },
  { value: "1014", option: "KAJANG" },
  { value: "1015", option: "KAPAR" },
  { value: "1016", option: "KLANG" },
  { value: "1017", option: "KERLING" },
  { value: "1018", option: "K. KUBU BHARU" },
  { value: "1019", option: "KUALA LUMPUR" },
  { value: "1020", option: "KUALA SELANGOR" },
  { value: "1021", option: "NILAI" },
  { value: "1022", option: "MANTIN" },
  { value: "1023", option: "PELABUHAN KLANG" },
  { value: "1024", option: "PETALING JAYA" },
  { value: "1025", option: "PUCHONG" },
  { value: "1026", option: "PULAU CAREY" },
  { value: "1027", option: "PULAU KETAM" },
  { value: "1028", option: "PULAU INDAH" },
  { value: "1029", option: "RANTAU PANJANG" },
  { value: "1030", option: "RASA" },
  { value: "1031", option: "RAWANG" },
  { value: "1032", option: "SABAK BERNAM" },
  { value: "1033", option: "SEKINCHAN" },
  { value: "1034", option: "SEMENYIH" },
  { value: "1035", option: "SEPANG" },
  { value: "1036", option: "SERENDAH" },
  { value: "1037", option: "SERI KEMBANGAN" },
  { value: "1038", option: "SHAH ALAM" },
  { value: "1039", option: "SUBANG JAYA" },
  { value: "1040", option: "SG AYER TAWAR" },
  { value: "1041", option: "SUNGAI BESAR" },
  { value: "1042", option: "SUNGAI BULOH" },
  { value: "1043", option: "SUNGAI PELEK" },
  { value: "1044", option: "TANJONG KARANG" },
  { value: "1045", option: "TANJONG SEPAT" },
  { value: "1046", option: "TELOK P. GARANG" },
  { value: "1047", option: "UKM BANGI" },
  { value: "1048", option: "UPM SERDANG" },
  { value: "1049", option: "HULU BERNAM" },
  { value: "1050", option: "BDR. BARU BANGI" },
  { value: "1051", option: "PUTRAJAYA(SEBELUM 1.2.2001)" },
  { value: "1052", option: "CYBERJAYA" },
  { value: "1053", option: "SELAYANG" },
  { value: "1087", option: "BANDAR BARU SUNGAI BULOH" },
  { value: "1088", option: "ULU YAM BARU" },
  { value: "1089", option: "GOMBAK" },
  { value: "1090", option: "SERDANG" },
  { value: "1092", option: "CHERAS" },
  { value: "1095", option: "BANDAR PUNCAK ALAM" },
  { value: "1096", option: "BANDAR PUNCAK ALAM" }
];

const TERENGGANU = [
  { value: "1100", option: "TERENGGANU" },
  { value: "1101", option: "AJIL" },
  { value: "1102", option: "BESUT" },
  { value: "1103", option: "BUKIT BESI" },
  { value: "1104", option: "DUNGUN" },
  { value: "1105", option: "JERTIH" },
  { value: "1106", option: "BDR PERMAISURI" },
  { value: "1107", option: "KEMAMAN" },
  { value: "1108", option: "KEMASEK" },
  { value: "1109", option: "KIJAL" },
  { value: "1110", option: "KUALA BERANG" },
  { value: "1111", option: "KUALA BESUT" },
  { value: "1112", option: "KUALA TERENGGANU" },
  { value: "1113", option: "MARANG" },
  { value: "1114", option: "PAKA" },
  { value: "1115", option: "KERTEH" },
  { value: "1116", option: "MUKTAFI BILLAH SHAH" },
  { value: "1117", option: "KAMPONG RAJA" },
  { value: "1118", option: "CUKAI" },
  { value: "1121", option: "KUALA NERUS" },
  { value: "1122", option: "BANDAR KETENGAH JAYA" }
];

const SABAH = [
  { value: "1200", option: "SABAH" },
  { value: "1201", option: "BEAUFORT" },
  { value: "1202", option: "BELURAN" },
  { value: "1203", option: "BONGAWAN" },
  { value: "1204", option: "INANAM" },
  { value: "1205", option: "KENINGAU" },
  { value: "1206", option: "KOTA BELUD" },
  { value: "1207", option: "KOTA KINABALU" },
  { value: "1208", option: "KOTA MARUDU" },
  { value: "1209", option: "KUALA PENYU" },
  { value: "1210", option: "KUDAT" },
  { value: "1211", option: "KUNAK" },
  { value: "1212", option: "LAHAD DATU" },
  { value: "1213", option: "LAMAG" },
  { value: "1214", option: "LIKAS" },
  { value: "1215", option: "MEMBAKUT" },
  { value: "1216", option: "MENUMBUK" },
  { value: "1217", option: "NABAWAN" },
  { value: "1218", option: "PAPAR" },
  { value: "1219", option: "PENAMPANG" },
  { value: "1220", option: "RANAU" },
  { value: "1221", option: "SANDAKAN" },
  { value: "1222", option: "SEMPORNA" },
  { value: "1223", option: "SIPITANG" },
  { value: "1224", option: "TAMBUNAN" },
  { value: "1225", option: "TAMPARULI" },
  { value: "1226", option: "TANJUNG ARU" },
  { value: "1227", option: "TAWAU" },
  { value: "1228", option: "TENOM" },
  { value: "1229", option: "TUARAN" },
  { value: "1230", option: "K. KINABATANGAN" },
  { value: "1232", option: "PUTATAN" },
  { value: "1233", option: "TELUPID" }
];

const SARAWAK = [
  { value: "1300", option: "SARAWAK" },
  { value: "1301", option: "ASAJAYA" },
  { value: "1302", option: "BALINGIAN" },
  { value: "1303", option: "BARAM" },
  { value: "1304", option: "BAU" },
  { value: "1305", option: "BEKENU" },
  { value: "1306", option: "BELAGA" },
  { value: "1307", option: "BELAWAI" },
  { value: "1308", option: "BETONG" },
  { value: "1309", option: "BINTANGOR" },
  { value: "1310", option: "BINTULU" },
  { value: "1311", option: "DALAT" },
  { value: "1312", option: "DARO" },
  { value: "1313", option: "DEBAK" },
  { value: "1314", option: "ENGKILILI" },
  { value: "1315", option: "JULAU" },
  { value: "1316", option: "KABONG" },
  { value: "1317", option: "KANOWIT" },
  { value: "1318", option: "KAPIT" },
  { value: "1319", option: "KOTA SAMARAHAN" },
  { value: "1320", option: "KUCHING" },
  { value: "1321", option: "LAWAS" },
  { value: "1322", option: "LIMBANG" },
  { value: "1323", option: "LINGGA" },
  { value: "1324", option: "LONG LAMA" },
  { value: "1325", option: "LUBOK ANTU" },
  { value: "1326", option: "LUNDU" },
  { value: "1327", option: "MATU" },
  { value: "1328", option: "MIRI" },
  { value: "1329", option: "MUKAH" },
  { value: "1330", option: "NANGA MEDAMIT" },
  { value: "1331", option: "NIAH" },
  { value: "1332", option: "PEKENU" },
  { value: "1333", option: "PUSA" },
  { value: "1334", option: "ROBAN" },
  { value: "1335", option: "SARATOK" },
  { value: "1336", option: "SARIKEI" },
  { value: "1337", option: "SEBAUH" },
  { value: "1338", option: "SEBUYAU" },
  { value: "1339", option: "SERIAN" },
  { value: "1340", option: "SIMUNJAN" },
  { value: "1341", option: "SONG" },
  { value: "1342", option: "SPAOH" },
  { value: "1343", option: "SRI AMAN" },
  { value: "1344", option: "SUNDAR" },
  { value: "1345", option: "TATAU" },
  { value: "1346", option: "TEBAKANG" },
  { value: "1347", option: "SIBU" },
  { value: "1348", option: "BINTANGOR" },
  { value: "1349", option: "TEBEDU" },
  { value: "1378", option: "PAKAN" },
  { value: "1379", option: "SIBUTI" },
  { value: "1380", option: "OYA" },
  { value: "1381", option: "LAPANGAN TERBANG KOTA KINABALU" },
  { value: "1382", option: "MARUDI" },
  { value: "1383", option: "SIBURAN" }
];

const WP_KUALA_LUMPUR = [
  { value: "1400", option: "W.PERSEKUTUAN" },
  { value: "1401", option: "KUALA LUMPUR" },
  { value: "1402", option: "CHERAS" },
  { value: "1403", option: "BATU CAVES" }
];

const WP_LABUAN = [
    {value : '1501', option : 'W.P LABUAN'}
]

const WP_PUTRAJAYA = [
    {value : '1601', option : 'PUTRAJAYA'}
]